spring.application.name=testting-system

spring.datasource.url=jdbc:mysql://localhost:3306/rw100_testing_system?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

#t?o các b?ng ho?c các column ?ang thi?u so v?i sql
spring.jpa.hibernate.ddl-auto=update

#format caau sql log
spring.jpa.properties.hibernate.format_sql=true

spring.main.allow-bean-definition-overriding=true


jwt.expiration=10
jwt.secret=djmaskldmnakldnkajndkljandakjsdnsakjknkdnaksjd